const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Anchor,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.EveryTick
	];
};
self.C3_JsPropNameTable = [
	{ЗаднийФон: 0},
	{Твёрдый: 0},
	{рисунокУровень1: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Игрок: 0},
	{Шипы: 0},
	{Мышь: 0},
	{Клавиатура: 0},
	{Синусоида: 0},
	{СквознаяПлатформа: 0},
	{Спрайт3: 0},
	{Якорь: 0},
	{Сердечки: 0},
	{Ава: 0},
	{Ваншот: 0},
	{Норм: 0},
	{МожетСтрелять: 0},
	{Хпвраг: 0},
	{Пуля: 0},
	{УничтожениеВнеМакета: 0},
	{ПодвижныйВраг1: 0},
	{ПуляОгонь: 0},
	{ПуляЛед: 0},
	{СтенаВрага: 0},
	{Спрайт: 0},
	{ПереходУровня: 0},
	{Спрайт4: 0},
	{ЗаднийФон2: 0},
	{рисунокУровень2: 0},
	{Аудио: 0},
	{b7ed8ff9bd17620732144a1359f9b01c: 0},
	{бОСС: 0},
	{БОСС1: 0},
	{Спрайт2: 0},
	{Спрайт5: 0},
	{ХПИгрок: 0}
];

self.InstanceType = {
	ЗаднийФон: class extends self.ITilemapInstance {},
	рисунокУровень1: class extends self.ITilemapInstance {},
	Игрок: class extends self.ISpriteInstance {},
	Шипы: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Клавиатура: class extends self.IInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Сердечки: class extends self.ISpriteInstance {},
	Ава: class extends self.ISpriteInstance {},
	Ваншот: class extends self.ISpriteInstance {},
	ПодвижныйВраг1: class extends self.ISpriteInstance {},
	ПуляОгонь: class extends self.ISpriteInstance {},
	ПуляЛед: class extends self.ISpriteInstance {},
	СтенаВрага: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	ПереходУровня: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	ЗаднийФон2: class extends self.ITilemapInstance {},
	рисунокУровень2: class extends self.ITilemapInstance {},
	Аудио: class extends self.IInstance {},
	b7ed8ff9bd17620732144a1359f9b01c: class extends self.ISpriteInstance {},
	бОСС: class extends self.ITilemapInstance {},
	БОСС1: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {}
}